"""Make username mandatory

Revision ID: 732a4fd12399
Revises: bd7fadd256c7
Create Date: 2026-01-08 20:03:35.359903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '732a4fd12399'
down_revision: Union[str, None] = 'bd7fadd256c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Populate existing users with username from email (part before @)
    op.execute("UPDATE users SET username = split_part(email, '@', 1) WHERE username IS NULL")
    
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###



