"""Scope uniqueness to user and account

Revision ID: 7f2d14cb7f5a
Revises: 732a4fd12399
Create Date: 2026-01-09 11:55:05.009694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f2d14cb7f5a'
down_revision: Union[str, None] = '732a4fd12399'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitored_accounts_username'), table_name='monitored_accounts')
    op.create_index(op.f('ix_monitored_accounts_username'), 'monitored_accounts', ['username'], unique=False)
    op.create_unique_constraint('uix_user_username', 'monitored_accounts', ['user_id', 'username'])
    op.drop_index(op.f('ix_posts_x_post_id'), table_name='posts')
    op.create_index(op.f('ix_posts_x_post_id'), 'posts', ['x_post_id'], unique=False)
    op.create_unique_constraint('uix_author_xpostid', 'posts', ['author_id', 'x_post_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_author_xpostid', 'posts', type_='unique')
    op.drop_index(op.f('ix_posts_x_post_id'), table_name='posts')
    op.create_index(op.f('ix_posts_x_post_id'), 'posts', ['x_post_id'], unique=True)
    op.drop_constraint('uix_user_username', 'monitored_accounts', type_='unique')
    op.drop_index(op.f('ix_monitored_accounts_username'), table_name='monitored_accounts')
    op.create_index(op.f('ix_monitored_accounts_username'), 'monitored_accounts', ['username'], unique=True)
    # ### end Alembic commands ###



