"""Add user multi-tenancy

Revision ID: efc1496987ad
Revises: 01cb67711921
Create Date: 2026-01-08 19:17:52.910327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efc1496987ad'
down_revision: Union[str, None] = '01cb67711921'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. Monitored Accounts
    op.add_column('monitored_accounts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE monitored_accounts SET user_id = 1") # Assign to first user
    op.alter_column('monitored_accounts', 'user_id', nullable=False)
    op.create_index(op.f('ix_monitored_accounts_user_id'), 'monitored_accounts', ['user_id'], unique=False)
    op.create_foreign_key(None, 'monitored_accounts', 'users', ['user_id'], ['id'])

    # 2. Alert Rules
    op.add_column('alert_rules', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE alert_rules SET user_id = 1")
    op.alter_column('alert_rules', 'user_id', nullable=False)
    op.drop_index(op.f('ix_alert_rules_name'), table_name='alert_rules')
    op.create_index(op.f('ix_alert_rules_name'), 'alert_rules', ['name'], unique=False)
    op.create_index(op.f('ix_alert_rules_user_id'), 'alert_rules', ['user_id'], unique=False)
    op.create_foreign_key(None, 'alert_rules', 'users', ['user_id'], ['id'])

    # 3. Digests
    op.add_column('digests', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE digests SET user_id = 1")
    op.alter_column('digests', 'user_id', nullable=False)
    op.drop_index(op.f('ix_digests_digest_date'), table_name='digests')
    op.create_index(op.f('ix_digests_digest_date'), 'digests', ['digest_date'], unique=False)
    op.create_index(op.f('ix_digests_user_id'), 'digests', ['user_id'], unique=False)
    op.create_foreign_key(None, 'digests', 'users', ['user_id'], ['id'])

    # 4. Settings
    op.add_column('settings', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE settings SET user_id = 1")
    # Settings might not have user_id 1 if empty, but assuming at least one user exists
    # If no settings exist, update does nothing, nullable check fails? No, if empty table it's fine.
    # But if table has rows, they need user_id. We assume user 1 exists (created in previous step manually or via registration).
    # IF NO USER EXISTS, THIS WILL FAIL on NOT NULL constraint if there are rows.
    # We should probably insert a dummy user if none exists? 
    # For now, assuming user ID 1 exists because you registered one.
    op.alter_column('settings', 'user_id', nullable=False)
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=False)
    op.create_index(op.f('ix_settings_user_id'), 'settings', ['user_id'], unique=False)
    op.create_foreign_key(None, 'settings', 'users', ['user_id'], ['id'])

    # 5. Topics
    op.add_column('topics', sa.Column('user_id', sa.Integer(), nullable=True))
    op.execute("UPDATE topics SET user_id = 1")
    op.alter_column('topics', 'user_id', nullable=False)
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=False)
    op.create_index(op.f('ix_topics_user_id'), 'topics', ['user_id'], unique=False)
    op.create_foreign_key(None, 'topics', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'topics', type_='foreignkey')
    op.drop_index(op.f('ix_topics_user_id'), table_name='topics')
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    op.drop_column('topics', 'user_id')
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.drop_index(op.f('ix_settings_user_id'), table_name='settings')
    op.drop_index(op.f('ix_settings_key'), table_name='settings')
    op.create_index(op.f('ix_settings_key'), 'settings', ['key'], unique=True)
    op.drop_column('settings', 'user_id')
    op.drop_constraint(None, 'monitored_accounts', type_='foreignkey')
    op.drop_index(op.f('ix_monitored_accounts_user_id'), table_name='monitored_accounts')
    op.drop_column('monitored_accounts', 'user_id')
    op.drop_constraint(None, 'digests', type_='foreignkey')
    op.drop_index(op.f('ix_digests_user_id'), table_name='digests')
    op.drop_index(op.f('ix_digests_digest_date'), table_name='digests')
    op.create_index(op.f('ix_digests_digest_date'), 'digests', ['digest_date'], unique=True)
    op.drop_column('digests', 'user_id')
    op.drop_constraint(None, 'alert_rules', type_='foreignkey')
    op.drop_index(op.f('ix_alert_rules_user_id'), table_name='alert_rules')
    op.drop_index(op.f('ix_alert_rules_name'), table_name='alert_rules')
    op.create_index(op.f('ix_alert_rules_name'), 'alert_rules', ['name'], unique=True)
    op.drop_column('alert_rules', 'user_id')
    # ### end Alembic commands ###



